version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: simple_chatbot_image
    container_name: chatbot-backend
    ports:
    - "8001:80"
    environment:
    - GROQ_API_KEY=${GROQ_API_KEY}
    - TAVILY_API_KEY=${TAVILY_API_KEY}
    env_file:
    - backend/.env
    restart: unless-stopped

  streamlit-langgraph:
    build:
      context: ./ui
      dockerfile: Dockerfile.langgraph
    image: streamlit_langgraph_image
    container_name: streamlit-langgraph
    ports:
    - "8501:8501"
    environment:
    - API_URL=http://backend:80/api/search_graph
    depends_on:
    - backend
    restart: unless-stopped

  streamlit-mcp:
    build:
      context: ./ui
      dockerfile: Dockerfile.mcp
    image: streamlit_mcp_image
    container_name: streamlit-mcp
    ports:
    - "8502:8501"
    environment:
    - API_URL=http://backend:80/api/search_mcp
    depends_on:
    - backend
    restart: unless-stopped
